### PR TITLE
some recommendations and improvements around file handler

### PR DESCRIPTION
**Pull request by Qambar**

### CODE REVIEW

**Comment by Qambar** [comment]
Shashi, this version is working properly. I just tested it.

**Comment by Shashikant86** [comment]
@Qambar Thanks Qambar. I will merge it now

**Comment by Shashikant86** [comment]
@Qambar I have pushed new version with your changes also added you as Author. It's version 0.1.1. Let's test this version.

**Comment by Shashikant86** [comment]
@Qambar I am getting this error 

Users/shashi/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.7.9/lib/bundler/rubygems_integration.rb:309:in `block in replace_bin_path': undefined method`name' for nil:NilClass (NoMethodError)
    from /Users/shashi/.rvm/gems/ruby-1.9.3-p551/bin/driller:23:in `<main>'
    from /Users/shashi/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in`eval'
    from /Users/shashi/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

**Comment by Shashikant86** [comment]
@Qambar Your improvements now working in the version 0.1.2. Thanks a lot.

**Comment by Qambar** [comment]
no worries ! :+1:

**Pull request closed without merging**
